[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
sqd-contract-client = { git = "https://github.com/subsquid/sqd-network.git", rev = "4f3fc86",  version = "1.1.0" }
sqd-messages = { git = "https://github.com/subsquid/sqd-network.git", rev = "4f3fc86", version = "2.0.0", features = ["bitstring"] }
sqd-network-transport = { git = "https://github.com/subsquid/sqd-network.git", rev = "4f3fc86", version = "2.0.0" }
