[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
sqd-contract-client = { git = "https://github.com/subsquid/subsquid-network.git", rev = "1c44e39",  version = "1.0.7" }
sqd-messages = { git = "https://github.com/subsquid/subsquid-network.git", rev = "1c44e39", version = "2.0.0", features = ["bitstring", "assignment_writer"] }
sqd-network-transport = { git = "https://github.com/subsquid/subsquid-network.git", rev = "1c44e39", version = "2.0.0" }
