#schedule_interval_epochs: 1
#worker_inactive_timeout_sec: 120     # 2 min
#worker_stale_timeout_sec: 900        # 15 min
#worker_unreachable_timeout_sec: 300  # 5 min
#failed_dial_retry_sec: 60            # 1 min
#successful_dial_retry_sec: 3600      # 1 hour
#replication_factor: 2
#scheduling_unit_size: 10
#mixed_units_ratio: 0.1
#mixing_recent_unit_weight: 10.0
#worker_storage_bytes: 549755813888   # 512 GiB
#s3_endpoint: 'https://7a28e49ec5f4a60c66f216392792ac38.r2.cloudflarestorage.com/'
#dataset_buckets:
#  - 'ethereum-mainnet'
#scheduler_state_bucket: 'network-scheduler-state'

schedule_interval_epochs: 6
worker_inactive_timeout_sec: 600
worker_monitoring_interval_sec: 60
worker_stale_timeout_sec: 900
worker_unreachable_timeout_sec: 300
failed_dial_retry_sec: 60
successful_dial_retry_sec: 3600
replication_factor: 5
dynamic_replication: true
dyn_rep_capacity_share: 0.9
scheduling_unit_size: 10
worker_storage_bytes: 549755813888
mixed_units_ratio: 0.1
mixing_recent_unit_weight: 10
s3_endpoint: https://7a28e49ec5f4a60c66f216392792ac38.r2.cloudflarestorage.com
dataset_buckets:
  - ethereum-mainnet-1
  - bsc-mainnet-1
  - base-1
  - moonbeam-evm-1
network_state_name: network-state.json
scheduler_state_bucket: network-scheduler-state-test
supported_worker_versions: ">=1.0.0-rc3"
recommended_worker_versions: ">=1.0.0"
jail_unreachable: false
ignore_existing_conns: false
ping_processing_threads: 16
